name: ReSim CI

on:
  workflow_dispatch:
  pull_request_target:


env:
    EVENT_NUMBER:  ${{ github.event.number }}
    PR_SHA: ${{ github.event.pull_request.base.sha }}
    WORKSPACE: ${{ github.workspace }}
    # WORKSPACE: $GITHUB_WORKSPACE
jobs:
  run:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/matthiasbschaefer/om_image:latest
      options: --user=resimuser --rm
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with: 
            persist-credentials: false
      
      - name: Run script
        run: /work/run_scripts/run_tool.sh $GITHUB_WORKSPACE ${{ env.EVENT_NUMBER }} ${{ env.PR_SHA }} om