name: ReSim CI

on:
  workflow_dispatch:
  pull_request_target:


env:
    EVENT_NUMBER:  ${{ github.event.number }}
    PR_SHA: ${{ github.event.pull_request.base.sha }}
    WORKSPACE: ${{ github.workspace }}
jobs:
  run:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/matthiasbschaefer/om_image:latest
      options: |
        --user=root
        --rm
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with: 
            persist-credentials: false
      - name: Write SSH keys
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            host='212.227.63.234'
            hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
            ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
      
      - name: Run script
        run: python /work/run_scripts/OM_PR_compare_local.py ${{ env.PR_SHA }} ${{ env.EVENT_NUMBER }} Modelica ${{ env.WORKSPACE }}