name: ReSim CI

on:
  workflow_dispatch:
  pull_request_target:


env:
    EVENT_NUMBER:  ${{ github.event.number }}
    BASE_SHA: ${{ github.event.pull_request.base.sha }}
    PR_SHA: ${{ github.event.pull_request.head.sha }}
    WORKSPACE: ${{ github.workspace }}
    PR_SERVER: ${{ vars.LTX_PR_SERVER }}
    SCRIPT_DIR: ${{ vars.LTX_SCRIPT_DIR }}
    # WORKSPACE: $GITHUB_WORKSPACE
jobs:
  run_dymola:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/matthiasbschaefer/dymola_image:latest
      options: --user=resimuser --rm
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with: 
            persist-credentials: false
            fetch-depth: 0
      
      - name: prepare
        run: ${{ env.SCRIPT_DIR }}/prepare_tool.sh $GITHUB_WORKSPACE ${{ env.EVENT_NUMBER }} ${{ env.BASE_SHA }} ${{ env.PR_SHA }} dymola
        
      - name: run
        run: ${{ env.SCRIPT_DIR }}/run_tool.sh $GITHUB_WORKSPACE ${{ env.EVENT_NUMBER }} ${{ env.BASE_SHA }} dymola
  
  run_openmodelica:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/matthiasbschaefer/om_image:latest
      options: --user=resimuser --rm
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with: 
            persist-credentials: false
            fetch-depth: 0
      
      - name: prepare
        run: ${{ env.SCRIPT_DIR }}/prepare_tool.sh $GITHUB_WORKSPACE ${{ env.EVENT_NUMBER }} ${{ env.BASE_SHA }} ${{ env.PR_SHA }} om
        
      - name: run
        run: ${{ env.SCRIPT_DIR }}/run_tool.sh $GITHUB_WORKSPACE ${{ env.EVENT_NUMBER }} ${{ env.BASE_SHA }} om

  overview:
    runs-on: ubuntu-latest
    needs: [run_openmodelica, run_dymola]
    if: always()
    container:
      image: ghcr.io/matthiasbschaefer/om_image:latest
      options: --user=resimuser --rm
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
  
    
    steps:
      - name: create_overview
        run: ${{ env.SCRIPT_DIR }}/create_overview.sh ${{ env.EVENT_NUMBER }}
    
  publish_modelica:
    runs-on: ubuntu-latest
    needs: [overview]
    container:
      image: ghcr.io/matthiasbschaefer/om_image:latest
      options: --user=resimuser --rm
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}    
    environment: 
        name: modelica_report
        url: ${{ env.PR_SERVER }}/${{ env.EVENT_NUMBER }}/Modelica/report/PR_comparison_report.html url: ${{ vars.LTX_PR_SERVER }}

    steps:  
      - name: publish_modelica
        run: ${{ env.SCRIPT_DIR }}/publish_reports.sh ${{ env.EVENT_NUMBER }} Modelica

  
  publish_modelicatest:
    runs-on: ubuntu-latest
    needs: [overview]
    container:
      image: ghcr.io/matthiasbschaefer/om_image:latest
      options: --user=resimuser --rm
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}    
    environment: 
        name: modelica_report
        url: ${{ env.PR_SERVER }}/${{ env.EVENT_NUMBER }}/ModelicaTest/report/PR_comparison_report.html url: ${{ vars.LTX_PR_SERVER }}    
    
    steps:        
      - name: publish_modelicatest
        run: ${{ env.SCRIPT_DIR }}/publish_reports.sh ${{ env.EVENT_NUMBER }} ModelicaTest
